version: "3.8"

services:
  frontend:
    build: .
    container_name: more-tech-frontend-container
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
