export const enum ERouteNames {
  DEFAULT_ROUTE = "/",
  EMPTY_ROUTE = "",
  DASHBOARD_ROUTE = "dashboard",
  DASHBOARD_ADMIN_ROUTE = "dashboard-admin",
  VACANCY_ROUTE = "vacancy/:vacancyId",
  VACANCY_DETAIL_ROUTE = "vacancy",
  VOICE_ROUTE = "voice",
  VOICE_DETAIL_ROUTE = "voice/:voiceId",
  STATISTICS_ROUTE = "statistics",
  AUTH_ROUTE = "auth",
  LOGIN_ROUTE = "login",
  REGISTER_ROUTE = "register",
  RESULT_ROUTE = "result",
}
